from re import A
import boto3


AWS_KEY="<YOURAWSKEYGOESHERE>"
AWS_SECRET="<YOURAWSSECRETGOESHERE>"
AWS_REGION="<YOURAWSREGIONGOESHERE>"
BUCKET="<YOURBUCKETGOESHERE>"
BUCKETFILE="<YOURBUCKETFILEGOESHERE>"
FILENAME="<YOURFILENAMEAFTERDOWNLOADGOESHERE>"


 
s3 = boto3.client('s3', region_name=AWS_REGION, aws_access_key_id=AWS_KEY, aws_secret_access_key=AWS_SECRET)

s3.download_file(BUCKET, BUCKETFILE, FILENAME)